"""
EXIF data extraction utilities for the Image Catalog TUI application.
"""

import json
import logging
from typing import Dict, Optional, Tuple, Any

try:
    from PIL import Image, ExifTags
    from PIL.PngImagePlugin import PngInfo
except ImportError:
    logging.error("PIL not installed. EXIF extraction will not work.")


def get_exif_data(image_path: str) -> Dict[str, Any]:
    """
    Extract EXIF data from an image file.
    
    Args:
        image_path: Path to the image file
        
    Returns:
        Dictionary containing EXIF data
    """
    exif_data = {}
    
    try:
        with Image.open(image_path) as img:
            # Get standard EXIF data
            if hasattr(img, '_getexif') and img._getexif():
                for tag, value in img._getexif().items():
                    if tag in ExifTags.TAGS:
                        exif_data[ExifTags.TAGS[tag]] = value
            
            # Get PNG text data (used by Midjourney and Fooocus)
            if img.format == 'PNG' and hasattr(img, 'text'):
                for key, value in img.text.items():
                    exif_data[f"PNG:{key}"] = value
                    
        return exif_data
        
    except Exception as e:
        logging.error(f"Error extracting EXIF data from {image_path}: {e}", exc_info=True)
        return {}


def is_fooocus_image(exif_data: Dict[str, Any], scheme_field: str = "PNG:Fooocus_scheme") -> bool:
    """
    Check if an image was generated by Fooocus based on EXIF data.
    
    Args:
        exif_data: Dictionary containing EXIF data
        scheme_field: Field name to check for Fooocus scheme
        
    Returns:
        True if the image is a Fooocus image, False otherwise
    """
    return scheme_field in exif_data and exif_data[scheme_field] == "fooocus"


def is_midjourney_image(exif_data: Dict[str, Any], author_field: str = "PNG:Author", author_value: str = "aardvark_fike") -> bool:
    """
    Check if an image was generated by Midjourney based on EXIF data.
    
    Args:
        exif_data: Dictionary containing EXIF data
        author_field: Field name to check for Midjourney author
        author_value: Expected author value for Midjourney images
        
    Returns:
        True if the image is a Midjourney image, False otherwise
    """
    return author_field in exif_data and exif_data[author_field] == author_value


def parse_fooocus_metadata(exif_data: Dict[str, Any], parameters_field: str = "PNG:Parameters") -> Dict[str, Any]:
    """
    Parse Fooocus metadata from EXIF data.
    
    Args:
        exif_data: Dictionary containing EXIF data
        parameters_field: Field name containing Fooocus parameters
        
    Returns:
        Dictionary containing parsed Fooocus metadata
    """
    if parameters_field not in exif_data:
        return {}
        
    try:
        # Parse JSON data from parameters field
        parameters = exif_data[parameters_field]
        return json.loads(parameters)
    except Exception as e:
        logging.error(f"Error parsing Fooocus metadata: {e}", exc_info=True)
        return {}


def parse_midjourney_metadata(exif_data: Dict[str, Any], description_field: str = "PNG:Description") -> Dict[str, Any]:
    """
    Parse Midjourney metadata from EXIF data.
    
    Args:
        exif_data: Dictionary containing EXIF data
        description_field: Field name containing Midjourney description
        
    Returns:
        Dictionary containing parsed Midjourney metadata
    """
    if description_field not in exif_data:
        return {}
        
    try:
        description = exif_data[description_field]
        prompt, job_id = parse_midjourney_description(description)
        
        return {
            "description": description,
            "prompt": prompt,
            "jobid": job_id
        }
    except Exception as e:
        logging.error(f"Error parsing Midjourney metadata: {e}", exc_info=True)
        return {}


def parse_midjourney_description(description: str) -> Tuple[str, str]:
    """
    Parse Midjourney description into prompt and job ID.
    
    Args:
        description: Midjourney description string
        
    Returns:
        Tuple containing (prompt, job_id)
    """
    job_id = ""
    prompt = description
    
    # Extract job ID if present
    if "Job ID:" in description:
        parts = description.split("Job ID:")
        prompt = parts[0].strip()
        job_id = parts[1].strip()
    
    return prompt, job_id
